[package]
name = "bifrost-s3"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
aws-config.workspace = true
aws-credential-types.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-async.workspace = true
aws-smithy-runtime-api-macros.workspace = true
aws-smithy-types.workspace = true
bifrost-common = { path = "../bifrost-common" }
bifrost-storage = { path = "../bifrost-storage" }
chrono.workspace = true
futures-util = "0.3"
http-body = "1"
http-body-util = "0.1"
tokio-util = { version = "0.7", features = ["io"] }
url.workspace = true

[dev-dependencies]
bytes.workspace = true
tokio.workspace = true
